CREATE DATABASE data_tranformation;
GO
USE data_tranformation;
GO


DROP TABLE IF EXISTS Communication;
DROP TABLE IF EXISTS MeetingAttendees;
DROP TABLE IF EXISTS Participant;
DROP TABLE IF EXISTS Speaker;
DROP TABLE IF EXISTS Content;
DROP TABLE IF EXISTS Subject;
DROP TABLE IF EXISTS CommunicationTypes;

CREATE TABLE CommunicationTypes(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL
);

CREATE TABLE Subject(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	
);

CREATE TABLE Content(
	ID NVARCHAR(255) PRIMARY KEY,
	Title NVARCHAR(255),
	Duration DECIMAL(6,3),
	AudioUrl NVARCHAR(255),
	VideoUrl NVARCHAR(255),
	Date DATETIME,
	HostEmail NVARCHAR(255),
	CalendarRef NVARCHAR(255),
	TranscriptUrl NVARCHAR(255),
	OrganizerEmail NVARCHAR(255)
);

CREATE TABLE Speaker(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(255) NOT NULL,
	ContentID NVARCHAR(255) NOT NULL,
	FOREIGN KEY(ContentID) REFERENCES Content(ID)
);

CREATE TABLE Participant(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Email NVARCHAR(255) NOT NULL,
	ContentID NVARCHAR(255) NOT NULL,
	FOREIGN KEY(ContentID) REFERENCES Content(ID)
);

CREATE TABLE MeetingAttendees(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(255),
	Email NVARCHAR(255),
	Location NVARCHAR(255),
	DisplayName NVARCHAR(255),
	PhoneNumber NVARCHAR(255),
	ContentID NVARCHAR(255) NOT NULL,
	FOREIGN KEY(ContentID) REFERENCES Content(ID)
);

CREATE TABLE Communication(
	ID NVARCHAR(255) PRIMARY KEY,
	CommunicationTypeID INT NOT NULL,
	ContentID NVARCHAR(255) NOT NULL,
	SourceID NVARCHAR(255),
	IngestedAt DATETIME2,
	ProcessedAt DATETIME2,
	IsProcessed BIT NOT NULL DEFAULT 0,
	SubjectID INT NOT NULL,
	FOREIGN KEY(CommunicationTypeID) REFERENCES CommunicationTypes(ID),
	FOREIGN KEY(SubjectID) REFERENCES Subject(ID),
	FOREIGN KEY(ContentID) REFERENCES Content(ID)
);